### GET /configuratioin/dimdeviceinfo/info/{id}
GET http://localhost:8888/configuration/dimdeviceinfo/info/26
Accept: application/json

### GET /configuratioin/dimdeviceinfo/list
GET http://localhost:8888/configuration/dimdeviceinfo/list?page=2&limit=2&key=
Accept: application/json

### POST /configuratioin/dimdeviceinfo/save
POST http://localhost:8888/configuration/dimdeviceinfo/save
Content-Type: application/json

{
  "deviceName": "wjl-test2",
  "deviceIp": "1.1.1.2",
  "snmpName": "wjl2",
  "udpPort": 161,
  "deviceRemark": "xxxxxxx"
}

### POST /configuratioin/dimdeviceinfo/update
POST http://localhost:8888/configuration/dimdeviceinfo/update
Content-Type: application/json

{
  "id": 36,
  "deviceName": "wjl-testxxxxxxxx",
  "deviceIp": "1.1.1.1",
  "snmpName": "wjl",
  "udpPort": 161,
  "deviceRemark": "qqqq"
}

### POST /configuratioin/dimdeviceinfo/delete
POST http://localhost:8888/configuration/dimdeviceinfo/delete
Content-Type: application/json

[
  33,
  34
]