#### 首页数据
POST http://localhost:8888/traffic/dwsTotalTraffic/home
Content-Type: application/json

{
  "startTime": "2024-10-19 23:00:00",
  "endTime": "2024-10-29 23:00:00"
}

#### 获取字典
GET http://localhost:8888/configuration/dimDict/infoList/isp
